money-for-rabbit/src/pages/home/Home.jsx

```
public
- images
src
- components
- button
- Button.jsx
- input
- Input.jsx
- pages
- home
- Home.jsx
- styles 
- layout
- Layout.jsx
```

:sparkles: (halam/setting/#1) 폴더구조 생성

---

money-for-rabbit/src/index.js
money-for-rabbit/src/pages/home/Home.jsx

- 07 ~ 16 : afternoon
- 17 ~ 18 : dusk
- 19 ~ 06 : night

시간에 따른 배경 이미지 변화

---

money-for-rabbit/src/components/input/Input.jsx
money-for-rabbit/src/index.css

`type`, `style`, `placeholder` 를 props로 받아서 사용합니다.
- type: 기존 input 태그의 type을 의미합니다. 'text', 'email', 'password'등을 사용할 수 있습니다.
- style: 
- 로그인/회원가입 : `'sign'`
- 닉네임 변경 : `'editNickname'`
- 금액 입력 : `'price'`
- placeholder: input 에서 보여지는 placeholder 입니다.

Input 컴포넌트 퍼블리싱

---

money-for-rabbit/src/App.jsx
money-for-rabbit/src/pages/user-page/UserPage.jsx
money-for-rabbit/src/utils/getDynamicImage.js

🚧 (taeyoung/#17) 남이 보는 마이페이지 퍼블리싱

---

money-for-rabbit/src/components/input/Input.jsx
money-for-rabbit/src/pages/withdrawal/Done.jsx
money-for-rabbit/src/styles/palette.js

- 오타 수정 `midium` -> `medium`
- palette 적용
- Input 컴포넌트
- 회원탈퇴 완료 페이지

palette 오타 수정 및 적용

---

money-for-rabbit/src/components/button/BoxButton.jsx
money-for-rabbit/src/components/button/TextButton.jsx
money-for-rabbit/src/pages/error/NotFound.jsx
money-for-rabbit/src/pages/user-page/UserPage.jsx
money-for-rabbit/src/styles/common.js
money-for-rabbit/src/styles/palette.js

♻️ (taeyoung/#25) palette 개선

---

money-for-rabbit/src/pages/home/Home.jsx
money-for-rabbit/src/styles/layout/Layout.jsx

- 레이아웃 배경색 제거
- 첫화면 화면클릭 문구 너비 수정

배포환경에서의 디자인 수정

---

money-for-rabbit/src/pages/user-page/WriteMessage.jsx

:truck: (taeyoung/#57) commonAxios 파일 이동에 따른 import 경로 수정

---

money-for-rabbit/src/App.jsx
money-for-rabbit/src/pages/home/Home.jsx
money-for-rabbit/src/styles/layout/Layout.jsx

:lipstick: 빈공간 배경영상 추가

---

money-for-rabbit/src/email/index.xhtml

:sparkles: (halam/#75) 이메일 템플릿 완성

---

money-for-rabbit/src/pages/letter/LetterList.jsx
money-for-rabbit/src/styles/layout/Layout.jsx

현재 데이터 불러와서 리스트 화면에 그려주고, 페이지네이션 처리까지 구현했습니다.
로그인한 토큰 정보 처리와 쪽지 클릭 시 해당 쪽지 url로 이동하는 것은 미구현 상태입니다.

쪽지 목록 조회 페이지 구현 중

---

money-for-rabbit/src/pages/home/Home.jsx

:adhesive_bandage::lipstick: (halam/#137) 첫화면 안내문구 가운데 배치

---

money-for-rabbit/src/index.css

(halam/#140) password input 입력값 안 보이는 이슈 해결 위해 폰트 변경

---

money-for-rabbit/public/index.html

:sparkles::lipstick: (halam/#129) 오픈그래프 썸네일 지정

---

money-for-rabbit/public/index.html

:lipstick: (halam/#129) 오픈그래프 썸네일 사진 사이즈 조절

---

money-for-rabbit/src/email/no-received-mail.html
money-for-rabbit/src/email/received-mail.html

세뱃돈을 받은 사람과 못 받은 사람에게 보내는 이메일 템플릿 완성

22일 세뱃돈 오픈 메일용 이메일 템플릿 완성

---

money-for-rabbit/src/pages/home/Home.jsx

- 로그인이 되어 있다면 클릭했을 때 마이페이지로 이동
- 로그인이 안 되어 있다면 클릭했을 때 로그인 모달 오픈

:sparkles: (halam/#152) 로그인 여부에 따라 첫화면에서 클릭했을 때 다르게 보여주기

---

money-for-rabbit/src/pages/letter/Letter.jsx

받은 쪽지 캡쳐 시 화면과 다르게 캡쳐되는 이슈 해결

---

money-for-rabbit/src/App.jsx
money-for-rabbit/src/pages/admin/Admin.jsx
money-for-rabbit/src/pages/admin/admin.css

관리자 페이지 세팅

---

money-for-rabbit/src/pages/letter/Box.jsx
money-for-rabbit/src/pages/letter/Letter.jsx
money-for-rabbit/src/pages/letter/LetterList.jsx
money-for-rabbit/src/pages/letter/PageNum.jsx

|첫번째 그룹|중간 그룹|마지막 그룹
|--|--|--|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/87893624/213134754-f13a1272-6b3f-47eb-8a9c-cfef1c53f333.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/87893624/213134957-77f85e46-9566-4e35-b5f4-f306d98317e1.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/87893624/213135013-349973bd-be40-49bb-b1a3-933892cb74db.png">

:sparkles::zap: (halam/#164) 그룹화를 통한 페이지네이션 기능 개선

---

money-for-rabbit/src/components/modal/Modal.jsx
money-for-rabbit/src/index.css
money-for-rabbit/src/pages/admin/admin.css
money-for-rabbit/src/pages/home/Home.jsx
money-for-rabbit/src/pages/letter/Letter.jsx
money-for-rabbit/src/pages/letter/LetterList.jsx
money-for-rabbit/src/pages/user-page/UserPage.jsx

- 첫페이지
- 마이페이지
- 쪽지 목록 조회 페이지
- 쪽지 상세 조회 페이지

:iphone: (halam/#160) 반응형 디자인

---

money-for-rabbit/src/components/input/Input.jsx
money-for-rabbit/src/pages/user-page/SelectMoney.jsx

|0원 이하|100만원 초과|
|--|--|
| <img width="384" alt="image" src="https://user-images.githubusercontent.com/87893624/213665556-f3214fdb-b133-4347-9d7b-439a7e0fcb26.png">| <img width="384" alt="image" src="https://user-images.githubusercontent.com/87893624/213665589-3ca63d05-9791-4f38-bff2-b5647f245206.png">

:sparkles: (halam/#181) 입력한 세뱃돈의 금액이 최소 또는 최대 이상의 금액일 경우 alert로 문구 띄우기

---

money-for-rabbit/src/pages/letter/LetterList.jsx
money-for-rabbit/src/pages/user-page/UserPage.jsx

- 절구 클릭 시 alert 문구 띄우고 페이지 이동 x
- url로 쪽지 목록 페이지 접근 시 문구 띄우기

:sparkles: (halam/#167) 설날인 22일 이전에 안 보여주는 페이지 추가

---

money-for-rabbit/src/pages/withdrawal/Withdrawal.jsx

|before|after|
|--|--|
| <img width="384" alt="image" src="https://user-images.githubusercontent.com/87893624/213696536-48243402-8952-4cf7-af89-68ef51e87bc0.png">| <img width="384" alt="image" src="https://user-images.githubusercontent.com/87893624/213696870-1f75280e-4df8-4c1e-a89f-669579d945d4.png">

:speech_balloon: (halam/#189) 회원 탈퇴 시 작성했던 세뱃돈과 덕담이 사라진다는 안내문구 추가
